rule H5toH5AD:
    input:
        script = "scripts/H5toH5AD.py",
        files = "rawdata/h5"
    output:
        h5ad = directory("procdata/h5ad")
    container:
        "docker://gcfntnu/scanpy:1.7.0"
    shell:
        """
        mkdir -p logs
	python {input.script} -i {input.files} -o {output.h5ad} -n integrated > logs/H5toH5AD.PYTHONout 2>&1
        """

rule S3toH5AD:
    input:
        script = "scripts/S3toH5AD.R",
        object = "rawdata/seurat3"
    output:
        h5ad = directory("procdata/h5ad")
    container:
        "docker://satijalab/seurat:4.0.1"
    shell:
        """
        mkdir -p logs
	Rscript {input.script} {input.object} {output.h5ad} > logs/S3toH5AD.Rout 2>&1
        """
rule S2toS3:
    input:
        script = "scripts/S2toS3.R",
        object = "rawdata/seurat2"
    output:
        out = directory("procdata/seurat3")
    container:
        "docker://satijalab/seurat:4.0.1"
    shell:
        """
        mkdir -p logs
	Rscript {input.script} {input.object} {output.out} > logs/S2toS3.Rout 2>&1
        """

